services:
  api:
    build:
      context: .
      dockerfile: packages/translation-api/Dockerfile
    container_name: translation_api
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=translations_db

  postgres:
    image: postgres:15-alpine
    container_name: translation_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=translations_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d translations_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: